# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  pool: sonic-armhf-t3
  jobs:
  - job: Build
    timeoutInMinutes: 120
    steps:
    - script: |
        set -x
        sudo ls -l /
        sudo lsblk
        sudo df -h
        sudo ls -l /dev/disk/azure/scsi1
        docker run --rm debian:buster uname -m
        pwd
        sudo ls -l /nfs
      displayName: test
    - template: template-showagent.yml
